name: author-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: make install
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Generate key
        run: php artisan key:generate --env=testing
      - name: Run linter
        run: make lint
      - name: Create Database
        run: |
          touch database/database.sqlite
          php artisan migrate
      - name: Launch Vite
        run: |
          npm install
          npm run build
